// Seed data for development/testing
export const seedData = {
  users: [
    {
      id: "user-teacher-1",
      email: "teacher@example.com",
      name: "John Doe",
      role: "teacher" as const,
      institution: "UPC",
      passwordHash: "2f8f3885377e8ea2",
      salt: "seed-teacher",
      createdAt: new Date(),
    },
    {
      id: "user-admin-1",
      email: "admin@example.com",
      name: "Admin User",
      role: "admin" as const,
      institution: "UPC",
      passwordHash: "de5d2cabf8f7e4a5",
      salt: "seed-admin",
      createdAt: new Date(),
    },
  ],
  courses: [
    {
      id: "course-math-101",
      userId: "user-teacher-1",
      title: "Mathématiques L2",
      subject: "Mathématiques",
      semester: "S1",
      description: "Introduction au calcul intégral",
      content: "Rappels, intégrales définies, primitives et applications.",
      summary: "Cours d'introduction au calcul intégral.",
      createdAt: new Date(),
    },
    {
      id: "course-phys-101",
      userId: "user-teacher-1",
      title: "Physique L2",
      subject: "Physique",
      semester: "S1",
      description: "Introduction à la mécanique",
      content: "Cinématique, dynamique et lois de Newton.",
      summary: "Cours de base en mécanique.",
      createdAt: new Date(),
    },
  ],
  students: [
    {
      id: "student-1",
      courseId: "course-math-101",
      firstName: "Alice",
      lastName: "Mukendi",
      matricule: "UPC001",
      createdAt: new Date(),
    },
  ],
  exams: [
    {
      id: "exam-midterm-1",
      courseId: "course-math-101",
      title: "Midterm Exam",
      instructions: "Répondez à toutes les questions.",
      totalPoints: 20,
      durationMinutes: 120,
      difficulty: "moyen" as const,
      type: "mixte" as const,
      questions: [],
      createdAt: new Date(),
    },
    {
      id: "exam-final-1",
      courseId: "course-math-101",
      title: "Final Exam",
      instructions: "Justifiez vos réponses.",
      totalPoints: 20,
      durationMinutes: 180,
      difficulty: "difficile" as const,
      type: "ouvert" as const,
      questions: [],
      createdAt: new Date(),
    },
  ],
  grades: [
    {
      id: "grade-1",
      courseId: "course-math-101",
      studentId: "student-1",
      examId: "exam-midterm-1",
      scannedText: "Réponses OCR de démonstration",
      imageUri: null,
      score: 15,
      maxScore: 20,
      appreciation: "Bonne compréhension générale.",
      strengths: ["Bonne application des méthodes"],
      weaknesses: ["Explications incomplètes"],
      suggestion: "Renforcer la précision des justifications.",
      validated: false,
      createdAt: new Date(),
    },
  ],
};